test(barplot): add unit tests for barplot
xability/py_maidr pull request #20
Opened 2024-02-23 00:33 UTC by SaaiVenkat

2024-02-23 00:39 UTC, jooyoungseo requested changes
Great. Could you please add GitHub action to trigger all the unit test on every push?

2024-02-23 14:51 UTC, SaaiVenkat commented
> eat. Could you please add GitHub action to trigger all the unit test on every push?

Sure @jooyoungseo . I'll let you know once I have added the action.

2024-02-23 14:54 UTC, jooyoungseo commented
@SaaiVenkat When you add the CI, please add `tox` like you did before so that we can check the unit tests against other Python versions.

2024-02-26 06:49 UTC, SaaiVenkat commented
> @SaaiVenkat When you add the CI, please add `tox` like you did before so that we can check the unit tests against other Python versions.

I have added tox to trigger the tests on every push and pull request

2024-02-26 15:28 UTC, jooyoungseo approved these changes

2024-03-05 21:21 UTC, merged